### ISSUE TITLE
Error fetching API data

### ISSUE THREAD

**Issue by mauirixxx** [c20xh2/tvfph#1]
Aloha, went to check out your script today, ran into an issue using CentOS 7

I did the following: 
* yum install python34-pip
* pip3 install --upgrade pip
* pip3 install requests

Doing a pip3 show requests:
[root@pi-hole phv]# pip3 show requests
Name: requests
Version: 2.18.4
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /usr/lib/python3.4/site-packages
Requires: certifi, urllib3, idna, chardet
Required-by:

So it's definitely installed. When I run:
`[root@pi-hole phv]# python3 main.py -i 192.168.1.30`

I get:
`Error fetching API data, maybe a wrong WEBPASSWORD ?`

I've tried specifying the password via the command line, and I currently have it in WebPassword.txt as well. I've verified my api status is enabled via http://192.168.1.30/admin/api.php?status as well.

Any insights?

**Comment by c20xh2** [comment]
What is the output if you try to access in a browser ? :

```
http://192.168.1.30/admin/api.php?getQuerySources&auth=[WEBPASSWORD]
```

**Comment by mauirixxx** [comment]
JSON: blank page
Raw data: [ ]
Headers: https://i.imgur.com/Ip2Axpp.png

Figured a picture would be better.

**Comment by c20xh2** [comment]
Blank page usually come from a wrong password

Are you using the WEBPASSWORD found in 

```/etc/pihole/setupVars.conf ```  

It's not the same password as the one you use to login into the admin page

**Comment by mauirixxx** [comment]
I was not, I thought I had to use the raw password! I really don't know how I overlooked the instructions that said where to get the password from :D

Aaaaannnd problem solved, working perfectly now.

THANK YOU <3
